version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "IoT-Buzzer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fqcyavcflrh6"
s3_prefix = "IoT-Buzzer"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
